/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shopproject;

/**
 *
 * @author Afaq Qazi
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    public gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainTabbedPane = new javax.swing.JTabbedPane();
        userTabPanel = new javax.swing.JPanel();
        userTabSidePanel = new javax.swing.JPanel();
        userTabAccountBtn = new javax.swing.JButton();
        UserTabInventoryBtn = new javax.swing.JButton();
        userTabAccountPanel = new javax.swing.JPanel();
        userTabInvenoryPanel = new javax.swing.JPanel();
        adminTabPanel = new javax.swing.JPanel();
        adminTabSidePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userTabSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        userTabAccountBtn.setText("Account");
        userTabAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTabAccountBtnActionPerformed(evt);
            }
        });

        UserTabInventoryBtn.setText("inventory");
        UserTabInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserTabInventoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userTabSidePanelLayout = new javax.swing.GroupLayout(userTabSidePanel);
        userTabSidePanel.setLayout(userTabSidePanelLayout);
        userTabSidePanelLayout.setHorizontalGroup(
            userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabSidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userTabSidePanelLayout.createSequentialGroup()
                        .addComponent(userTabAccountBtn)
                        .addGap(4, 4, 4))
                    .addComponent(UserTabInventoryBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        userTabSidePanelLayout.setVerticalGroup(
            userTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userTabSidePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(userTabAccountBtn)
                .addGap(26, 26, 26)
                .addComponent(UserTabInventoryBtn)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        userTabPanel.add(userTabSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        userTabAccountPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout userTabAccountPanelLayout = new javax.swing.GroupLayout(userTabAccountPanel);
        userTabAccountPanel.setLayout(userTabAccountPanelLayout);
        userTabAccountPanelLayout.setHorizontalGroup(
            userTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        userTabAccountPanelLayout.setVerticalGroup(
            userTabAccountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        userTabPanel.add(userTabAccountPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, 580));

        userTabInvenoryPanel.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout userTabInvenoryPanelLayout = new javax.swing.GroupLayout(userTabInvenoryPanel);
        userTabInvenoryPanel.setLayout(userTabInvenoryPanelLayout);
        userTabInvenoryPanelLayout.setHorizontalGroup(
            userTabInvenoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        userTabInvenoryPanelLayout.setVerticalGroup(
            userTabInvenoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        userTabPanel.add(userTabInvenoryPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 0, 950, -1));

        MainTabbedPane.addTab("User Tab", userTabPanel);

        adminTabPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminTabSidePanel.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout adminTabSidePanelLayout = new javax.swing.GroupLayout(adminTabSidePanel);
        adminTabSidePanel.setLayout(adminTabSidePanelLayout);
        adminTabSidePanelLayout.setHorizontalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        adminTabSidePanelLayout.setVerticalGroup(
            adminTabSidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        adminTabPanel.add(adminTabSidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, -1));

        MainTabbedPane.addTab("Admin Tab", adminTabPanel);

        getContentPane().add(MainTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTabAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTabAccountBtnActionPerformed
        // TODO add your handling code here:
        this.userTabAccountPanel.setVisible(true);
        this.userTabInvenoryPanel.setVisible(false);
    }//GEN-LAST:event_userTabAccountBtnActionPerformed

    private void UserTabInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserTabInventoryBtnActionPerformed
        // TODO add your handling code here:
        this.userTabAccountPanel.setVisible(false);
        this.userTabInvenoryPanel.setVisible(true);
    }//GEN-LAST:event_UserTabInventoryBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane MainTabbedPane;
    private javax.swing.JButton UserTabInventoryBtn;
    private javax.swing.JPanel adminTabPanel;
    private javax.swing.JPanel adminTabSidePanel;
    private javax.swing.JButton userTabAccountBtn;
    private javax.swing.JPanel userTabAccountPanel;
    private javax.swing.JPanel userTabInvenoryPanel;
    private javax.swing.JPanel userTabPanel;
    private javax.swing.JPanel userTabSidePanel;
    // End of variables declaration//GEN-END:variables
}
